"""Stable machine-readable error codes for the P0 control plane."""

from __future__ import annotations

from enum import Enum


class ErrorCode(str, Enum):
    MANIFEST_INVALID = "P0_MANIFEST_INVALID"
    ASSET_MISSING = "P0_ASSET_MISSING"
    ENV_UNSUPPORTED = "P0_ENV_UNSUPPORTED"
    DEPENDENCY_UNDECLARED = "P0_DEPENDENCY_UNDECLARED"
    TEST_DISCOVERY_FAILED = "P0_TEST_DISCOVERY_FAILED"
    STALE_REFERENCE = "P0_STALE_REFERENCE"
    CODE_ORIGIN_MISMATCH = "P0_CODE_ORIGIN_MISMATCH"
    CACHE_DEPENDENCY_DETECTED = "P0_CACHE_DEPENDENCY_DETECTED"
    NETWORK_POLICY_VIOLATION = "P0_NETWORK_POLICY_VIOLATION"
    CHECK_FAILED = "P0_CHECK_FAILED"
    CHECK_ERROR = "P0_CHECK_ERROR"
    CHECK_SKIPPED = "P0_CHECK_SKIPPED"
    CHECK_INTERRUPTED = "P0_CHECK_INTERRUPTED"
    RESULT_MISSING = "P0_RESULT_MISSING"
    EVIDENCE_INCOMPLETE = "P0_EVIDENCE_INCOMPLETE"
    DOCUMENTATION_MISMATCH = "P0_DOCUMENTATION_MISMATCH"
    SCOPE_VIOLATION = "P0_SCOPE_VIOLATION"


FAILURE_ERROR_CODES = frozenset(
    code
    for code in ErrorCode
    if code
    not in {
        ErrorCode.CHECK_SKIPPED,
        ErrorCode.CHECK_INTERRUPTED,
        ErrorCode.RESULT_MISSING,
        ErrorCode.EVIDENCE_INCOMPLETE,
    }
)

INCOMPLETE_ERROR_CODES = frozenset(ErrorCode) - FAILURE_ERROR_CODES
